package com.boscloner.bosclonerv2.bluetooth;


public enum BluetoothDeviceStatus {
    CONNECTING,
    CONNECTED,
    DISCONNECTED,
    ERROR,
    STARTING_SERVICE_DISCOVERY,
    ERROR_STARTING_SERVICE_DISCOVERY,
    SERVICES_DISCOVERY_SUCCESS,
    ON_CHARACTERISTIC_READ,
    ON_CHARACTERISTIC_CHANGED,
    ON_DESCRIPTOR_WRITE,
    TRYING_TO_USE_EXISTING_CONNECTION,
    DISCONNECTING,
    CLOSED,
    INITIALIZATION_SUCCESS,
    ON_CHARACTERISTIC_WRITE, BLUETOOTH_OFF,
}
