package com.boscloner.bosclonerv2.bluetooth;

public enum FetchBluetoothDataStatus {
    CONNECTING,
    CONNECTED,
    LOADING,
    SET_TIME_SUCCESS,
    SET_TIME_ERROR,
    BATTERY_LEVEL_SUCCESS,
    CONTINUOUS_PR_DATA_EXISTS,
    CONTINIOUS_PR_DATA_EMPTY,
    CONTINIOUS_PR_DATA_RECEIVING,
    CONTINIOUS_PR_DATA_RECEIVED_SUCCESS,
    CONTINUOUS_SPO2_DATA_EXISTS,
    CONTINIOUS_SPO2_DATA_EMPTY,
    CONTINIOUS_SPO2_DATA_RECEIVING,
    CONTINIOUS_SPO2_DATA_RECEIVED_SUCCESS,
    DELETE_CONTINUOUS_PR_DATA_SUCCESS,
    DELETE_CONTINUOUS_SPO2_DATA_SUCCESS,
    DISCONNECTED,
    BLUETOOTH_OFF, ERROR
}